# Generated by Django 6.0.4 on 2026-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('parish', models.CharField(max_length=100)),
                ('land_location', models.CharField(max_length=150)),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_type', models.CharField(max_length=100)),
            ],
        ),
    ]
